# -*- coding: utf-8 -*-
"""1M1B internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kDuPME8fwN8ntJvVaPhNVhOyvgUm6yoV
"""

!pip install sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

knowledge_base = [
    "Budgeting helps track income and expenses to control spending.",
    "Saving regularly builds financial security for emergencies.",
    "Loans should be taken only after understanding interest rates and repayment terms.",
    "Insurance protects against financial loss due to unexpected events.",
    "Government schemes support education, healthcare, and income security.",
    "Avoid high-interest debt and prioritize essential expenses.",
    "Emergency funds should cover at least three months of expenses."
]

model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(knowledge_base, normalize_embeddings=True)
dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)
index.add(embeddings)

def retrieve_context(query):
    query_embedding = model.encode([query], normalize_embeddings=True)
    scores, indices = index.search(query_embedding, k=2)

    retrieved = [knowledge_base[i] for i in indices[0]]
    confidence = round(float(np.max(scores)) * 100, 2)
    accuracy = round(float(np.mean(scores)) * 100, 2)

    return retrieved, confidence, accuracy

def generate_response(context):
    response = "Here is some useful financial guidance based on your question:\n\n"
    for point in context:
        response += f"- {point}\n"
    response += "\nThis information is for educational purposes only."
    return response

while True:
    user_query = input("Ask a financial question (type 'exit' to quit): ")
    if user_query.lower() == "exit":
        break

    context, confidence, accuracy = retrieve_context(user_query)
    answer = generate_response(context)

    print("\nAssistant:", answer)
    print(f"\nConfidence Score: {confidence}%")
    print(f"Retrieval Accuracy: {accuracy}%\n")

